### ISSUE TITLE
The smallNORB link 

### ISSUE THREAD

**Issue by mritunjaymusale** [yl-1993/Matrix-Capsules-EM-PyTorch#2]
The smallNORB link is dead, can you please switch the link to some other server ?

**Comment by mritunjaymusale** [comment]
here's an alternative I found.


https://cdn-05.anonfile.com/w55eycg1b1/cc7a9270-1535268621/the-small-norb-dataset-v10.zip


https://anonfile.com/w55eycg1b1/the-small-norb-dataset-v10.zip

**Comment by yl-1993** [comment]
@mritunjaymusale Thanks for providing the external links. It seems that the official server is back online again.
