### ISSUE TITLE
How many Gaussians are in the GMM in EM Routing?

### ISSUE THREAD

**Issue by dmzou** [yl-1993/Matrix-Capsules-EM-PyTorch#7]
Thanks for this great resource! I am trying to understand the original paper and am using this code as a template.

I am not sure how EM routing is a form of GMM as described in the original paper. For example, how many Gaussians are we fitting? To what data and in what ambient dimension? 

It appears that the dimension of mu is 32x4x4=CxPxP.  https://github.com/YuxianMeng/Matrix-Capsules-pytorch, which you cite, has mu of size CxWxWxPxP where W is the size of the convolutional kernel. Is this correct?

**Comment by ZHAOZHIHAO** [comment]
Hi dmzou,

Gaussians are the centers of their receptive field in the lower layer.  This receptive field has a size of KxKxB where K is the size of the convolutional kernel. So we should  let the dimension of mu be CxPxP.

**Comment by dmzou** [comment]
Thanks! It's clear now.
